let permissions =[
    {   permission: "P1",
        object:"I_HOME",
        action:"read",
    },
    {   permission: "P2",
        object:"I_PROFILE",
        action:"write",
    },
    {   permission: "P3",
        object:"I_PROFILE",
        action:"read",
    },
    {   permission: "P4",
        object:"OFFER_COURSE",
        action:"write",
    },
    {   permission: "P4",
        object:"I_COURSES",
        action:"read",
    },
    {   permission: "P6",
        object:"I_COURSE_DETAILS",
        action:"read",
    },
    {   permission: "P7",
        object:"I_COURSE_DETAILS",
        action:"write",
    },
    {   permission: "P8",
        object:"OFFER_COURSE",
        action:"read",
    },
    {   permission: "P9",
        object:"I_ANNOUNCEMENT",
        action:"read",
    },
    {   permission: "P10",
        object:"I_ANNOUNCEMENT",
        action:"write",
    },
    {   permission: "P11",
        object:"I_RESOURCES",
        action:"read",
    },
    {   permission: "P12",
        object:"I_RESOURCES",
        action:"write",
    },
    {   permission: "P13",
        object:"I_RESOURCE",
        action:"read",
    },
    {   permission: "P14",
        object:"I_RESOURCE",
        action:"delete",
    },
    {   permission: "P15",
        object:"I_TESTS",
        action:"read",
    },
    {   permission: "P16",
        object:"I_TEST",
        action:"read",
    },
    {   permission: "P17",
        object:"I_TEST",
        action:"write",
    },
    {   permission: "P18",
        object:"I_TESTS",
        action:"write",
    },
    {   permission: "P19",
        object:"I_TEST_Q",
        action:"read",
    },
    {   permission: "P20",
        object:"I_TEST_A",
        action:"read",
    },
    {   permission: "P21",
        object:"I_TEST",
        action:"delete",
    },
    {   permission: "P22",
        object:"I_TEST_R",
        action:"read",
    },
    {   permission: "P23",
        object:"I_TEST_R",
        action:"write",
    },
    {   permission: "P24",
        object:"I_ASSIGNMENTS",
        action:"read",
    },
    {   permission: "P25",
        object:"I_ASSIGNMENTS",
        action:"write",
    },
    {   permission: "P26",
        object:"I_ASSIGNMENT",
        action:"read",
    },
    {   permission: "P27",
        object:"I_ASSIGNMENT",
        action:"delete",
    },
    {   permission: "P28",
        object:"I_ASSIGNMENT_SUB",
        action:"read",
    },
    {   permission: "P29",
        object:"I_COURSE_STUDENTS",
        action:"read",
    },
    {   permission: "P30",
        object:"I_COURSE_STUDENTS",
        action:"approve",
    },
    {   permission: "P31",
        object:"I_COURSE_ASSISTANTS",
        action:"read",
    },
    {   permission: "P32",
        object:"I_COURSE_ASSISTANTS",
        action:"approve",
    },
    {   permission: "P33",
        object:"I_QA",
        action:"read",
    },
    {   permission: "P34",
        object:"I_QA",
        action:"write",
    },
    {   permission: "P35",
        object:"I_ANSWER",
        action:"write",
    },
    {   permission: "P36",
        object:"I_ASSIGNMENT_SUBMISSIONS",
        action:"read",
    },
    {   permission: "P37",
        object:"I_ANNOUNCEMENTS",
        action:"read",
    },
    {   permission: "P38",
        object:"I_ATTANDANCE",
        action:"write",
    },
    {   permission: "P39",
        object:"I_ATTANDANCE",
        action:"read",
    },
    {   permission: "P40",
        object:"I_ATTANDANCE_DETAILS",
        action:"read",
    },
    {   permission: "P41",
        object:"I_ADD_ATTENDANCE",
        action:"read",
    },
    {   permission: "P42",
        object:"I_REPLY",
        action:"write",
    },
    {   permission: "P43",
        object:"I_EXAMS",
        action:"read",
    },
    {   permission: "P44",
        object:"I_ADDEXAM",
        action:"read",
    },
    {   permission: "P45",
        object:"I_ADDEXAM",
        action:"write",
    },
    {   permission: "P46",
        object:"I_EXAM",
        action:"read",
    },
    {   permission: "P47",
         object:"I_RESULT",
       action:"read",
    },
    {   permission: "P48",
        object:"I_ALL",
        action:"read",
    },
    {   permission: "P49",
        object:"HOD_MESSAGES",
        action:"read",
    },
    {   permission: "P50",
        object:"HOD_MESSAGES",
        action:"write",
    },
    {   permission: "P51",
        object:"HOME",
        action:"read",
    },
    {   permission: "P52",
        object:"COURSE",
        action:"read",
    },
    {   permission: "P53",
        object:"ABOUT",
        action:"read",
    },
    {   permission: "P54",
        object:"CONTACT",
        action:"read",
    },
    {   permission: "P55",
        object:"SERVICES",
        action:"read",
    },
    {   permission: "P56",
        object:"SEARCH",
        action:"write",
    },
    {   permission: "P57",
        object:"SEARCH_INST",
        action:"read",
    },
    {   permission: "P58",
        object:"SEARCH_COURSE",
        action:"read",
    },
    {   permission: "P59",
        object:"S_HOME",
        action:"read",
   },
   {   permission: "P60",
        object:"S_PROFILE",
        action:"read",
    },
    {   permission: "P62",
        object:"S_PROFILE",
        action:"write",
    },
    {   permission: "P63",
        object:"S_SEARCH",
        action:"write",
    },
    {   permission: "P64",
        object:"S_SEARCH_INST",
        action:"read",
    },
    {   permission: "P65",
        object:"S_SEARCH_COURSE",
        action:"read",
    },
    {   permission: "P66",
        object:"S_COURSE",
        action:"join",
    },
    {   permission: "P67",
        object:"S_COURSES",
        action:"read",
    },
    {   permission: "P68",
        object:"S_COURSE_DETAILS",
        action:"read",
    },
    {   permission: "P69",
        object:"S_JOIN_COURSES",
        action:"read",
    },
    {   permission: "P70",
        object:"S_ASSIGNMENT",
        action:"read",
    },
    {   permission: "P72",
        object:"S_RESOURCES",
        action:"read",
    },
    {   permission: "P73",
        object:"S_RESOURCE",
        action:"read",
    },
    {   permission: "P74",
        object:"S_ASSIGNMENTS",
        action:"read",
    },
    {   permission: "P75",
        object:"S_STUDENTS",
        action:"read",
    },
    {   permission: "P76",
        object:"S_ANNOUNCEMENT",
        action:"read",
    },
    {   permission: "P77",
        object:"S_TESTS",
        action:"read",
    },
    {   permission: "P78",
        object:"S_TEST_Q",
        action:"read",
    },
    {   permission: "P79",
        object:"S_TEST_ANSWER",
        action:"read",
    },
    {   permission: "P80",
        object:"S_QA",
        action:"read",
    },
    {   permission: "P81",
        object:"S_QA",
        action:"write",
    },
    {   permission: "P82",
        object:"S_ANSWER",
        action:"write",
    },
    {   permission: "P83",
        object:"S_ASSIGNMENT_SUBMIT",
        action:"write",
    },
    {   permission: "P84",
        object:"S_ASSIGNMENT_SUBMIT",
        action:"read",
    },
    {   permission: "P85",
        object:"S_ASSIGNMENT_SUBMISSION",
        action:"read",
    },
    {   permission: "P86",
        object:"S_REPLY",
        action:"write",
    },
    {   permission: "P87",
        object:"S_EXAMS",
        action:"read",
    },
    {   permission: "P88",
        object:"S_EXAM_START",
        action:"write",
    },
    {   permission: "P88",
        object:"S_EXAM_RESULT",
        action:"read",
    },

    {   permission: "P89",
        object:"S_EXAM_SUBMIT",
        action:"write",
    },
    {   permission: "P90",
        object:"S_EXAM_ENTER",
        action:"read",
    },
    {   permission: "P61",
        object:"S_INSTRUCTOR_CONTACT",
        action:"read",
    },
    {   permission: "P91",
        object:"SECOND",
        action:"read",
   },
   {   permission: "P92",
        object:"THIRD",
        action:"read",
   },
   {   permission: "P93",
        object:"FOURTH",
        action:"read",
   },
   {   permission: "P94",
       object:"A_HOME",   
       action:"read",   
   },
   {   permission: "P95",
       object:"A_PROFILE",   
       action:"read",   
   },
   {   permission: "P96",
       object:"A_PROFILE",   
       action:"write",   
   },
   {   permission: "P97",
       object:"A_SEARCH",   
       action:"write",   
   },
   {   permission: "P98",
       object:"A_SEARCH_INST",   
       action:"read",   
   },
   {   permission: "P99",
       object:"A_SEARCH",   
       action:"read",   
   },
   {   permission: "P100",
       object:"A_JOIN_COURSE",   
       action:"read",   
   },
   {   permission: "P101",
       object:"A_JOIN_COURSE",   
       action:"join",   
   },
   {   permission: "P102",
       object:"A_COURSES",   
       action:"read",   
   },
  
]
module.exports=permissions;